"""
Polygon zone manager for spatial analytics.

Defines geographic regions of interest within the camera frame and
tracks which objects are inside each zone. Generates structured events
for zone entry, zone exit, loitering, and crowd alerts.

Features:
    - Arbitrary polygon zones (not just rectangles)
    - Per-zone occupancy counting with entry/exit tracking
    - Dwell time measurement per object per zone
    - Configurable loitering threshold with debounce
    - Configurable crowd density threshold
    - Zone definitions loadable from JSON config file

Usage:
    zones = ZoneManager.from_config("data/zones_config.json")
    events = zones.update(tracked_objects)
    # → [ZoneEvent(type="ZONE_ENTRY", zone="Zone A", object_id=3), ...]
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import cv2
import numpy as np


@dataclass(frozen=True, slots=True)
class ZoneEvent:
    """A spatial event generated by the zone manager.

    Attributes:
        type:         Event type (ZONE_ENTRY, ZONE_EXIT, LOITERING, CROWD_ALERT).
        zone_name:    Name of the zone that triggered the event.
        object_id:    Track ID of the object involved (None for CROWD_ALERT).
        dwell_seconds: Time in zone (only populated for LOITERING events).
        occupancy:    Current number of people in the zone.
    """

    type: str
    zone_name: str
    object_id: int | None = None
    dwell_seconds: float = 0.0
    occupancy: int = 0


class Zone:
    """A single polygon region of interest with tracking state.

    Each zone independently tracks which objects are inside it,
    when they entered, and whether alerting conditions are met.
    """

    def __init__(
        self,
        name: str,
        points: list[tuple[int, int]],
        crowd_threshold: int = 3,
        loiter_seconds: int = 4,
    ):
        """Initialize a zone.

        Args:
            name:             Human-readable zone name (e.g., "Zone A").
            points:           Polygon vertices as [(x, y), ...].
            crowd_threshold:  Occupancy count that triggers a crowd alert.
            loiter_seconds:   Seconds before a person is flagged as loitering.
        """
        self.name = name
        self.polygon = np.array(points, dtype=np.int32)
        self.crowd_threshold = crowd_threshold
        self.loiter_seconds = loiter_seconds

        # Tracking state
        self.inside_ids: set[int] = set()
        self.enter_count: int = 0
        self.exit_count: int = 0
        self.dwell_start: dict[int, float] = {}

        # Alert state (prevents repeated alerts for the same condition)
        self._loiter_alerted: set[int] = set()
        self._crowd_alerted: bool = False

    def point_inside(self, point: tuple[int, int]) -> bool:
        """Test if a point lies inside this zone's polygon.

        Uses OpenCV's pointPolygonTest which implements the
        ray-casting algorithm. Returns True if the point is
        inside or on the boundary.
        """
        result = cv2.pointPolygonTest(
            self.polygon,
            (float(point[0]), float(point[1])),
            measureDist=False,
        )
        return result >= 0

    def update(self, tracked_objects: dict[int, tuple[int, int]]) -> list[ZoneEvent]:
        """Update zone state and generate events.

        This is the core method called every frame. It compares the
        current set of objects inside the zone to the previous frame's
        set and generates appropriate events.

        Args:
            tracked_objects: Dict of {track_id: (cx, cy)} from the tracker.

        Returns:
            List of ZoneEvent objects for this frame (may be empty).
        """
        events: list[ZoneEvent] = []
        now = time.time()

        # Determine which objects are currently inside this zone
        currently_inside: set[int] = set()
        for oid, centroid in tracked_objects.items():
            if self.point_inside(centroid):
                currently_inside.add(oid)

        # ── Entry events ─────────────────────────────────
        entered = currently_inside - self.inside_ids
        for oid in entered:
            self.enter_count += 1
            self.dwell_start[oid] = now
            events.append(ZoneEvent(
                type="ZONE_ENTRY",
                zone_name=self.name,
                object_id=oid,
                occupancy=len(currently_inside),
            ))

        # ── Exit events ──────────────────────────────────
        exited = self.inside_ids - currently_inside
        for oid in exited:
            self.exit_count += 1
            dwell = now - self.dwell_start.pop(oid, now)
            self._loiter_alerted.discard(oid)
            events.append(ZoneEvent(
                type="ZONE_EXIT",
                zone_name=self.name,
                object_id=oid,
                dwell_seconds=round(dwell, 1),
                occupancy=len(currently_inside),
            ))

        # ── Loitering detection ──────────────────────────
        for oid in currently_inside:
            if oid in self._loiter_alerted:
                continue  # Already alerted for this stint
            dwell = now - self.dwell_start.get(oid, now)
            if dwell >= self.loiter_seconds:
                self._loiter_alerted.add(oid)
                events.append(ZoneEvent(
                    type="LOITERING",
                    zone_name=self.name,
                    object_id=oid,
                    dwell_seconds=round(dwell, 1),
                    occupancy=len(currently_inside),
                ))

        # ── Crowd alert ──────────────────────────────────
        is_crowded = len(currently_inside) >= self.crowd_threshold
        if is_crowded and not self._crowd_alerted:
            self._crowd_alerted = True
            events.append(ZoneEvent(
                type="CROWD_ALERT",
                zone_name=self.name,
                occupancy=len(currently_inside),
            ))
        elif not is_crowded:
            self._crowd_alerted = False  # Reset when crowd disperses

        # Update state for next frame
        self.inside_ids = currently_inside

        return events

    def get_dwell(self, object_id: int) -> float:
        """Get current dwell time (seconds) for an object in this zone."""
        if object_id in self.dwell_start:
            return time.time() - self.dwell_start[object_id]
        return 0.0


class ZoneManager:
    """Manages a collection of zones and aggregates their events.

    Provides a unified `update()` method that processes all zones
    in a single call, returning a combined list of events.
    """

    def __init__(self, zones: list[Zone] | None = None):
        self.zones: list[Zone] = zones or []

    @classmethod
    def from_config(cls, config_path: str | Path) -> ZoneManager:
        """Load zones from a JSON configuration file.

        Expected format:
            [
                {
                    "name": "Zone A",
                    "points": [[100, 100], [400, 100], [400, 400], [100, 400]],
                    "crowd_threshold": 3,
                    "loiter_seconds": 4
                }
            ]
        """
        path = Path(config_path)
        if not path.exists():
            return cls([])

        with open(path) as f:
            zone_defs = json.load(f)

        zones = [
            Zone(
                name=z["name"],
                points=[tuple(p) for p in z["points"]],
                crowd_threshold=z.get("crowd_threshold", 3),
                loiter_seconds=z.get("loiter_seconds", 4),
            )
            for z in zone_defs
        ]
        return cls(zones)

    @classmethod
    def create_default(cls, frame_width: int, frame_height: int) -> ZoneManager:
        """Create a default zone covering the central 50% of the frame.

        Used when no zone config file exists — ensures the visual
        module always has at least one active zone for demonstrations.
        """
        margin = 0.25
        points = [
            (int(frame_width * margin), int(frame_height * margin)),
            (int(frame_width * (1 - margin)), int(frame_height * margin)),
            (int(frame_width * (1 - margin)), int(frame_height * (1 - margin))),
            (int(frame_width * margin), int(frame_height * (1 - margin))),
        ]
        return cls([Zone("Zone A", points)])

    def update(
        self, tracked_objects: dict[int, tuple[int, int]]
    ) -> list[ZoneEvent]:
        """Process all zones and return combined events."""
        all_events: list[ZoneEvent] = []
        for zone in self.zones:
            all_events.extend(zone.update(tracked_objects))
        return all_events

    def get_stats(self) -> list[dict[str, Any]]:
        """Get summary statistics for all zones."""
        return [
            {
                "name": z.name,
                "occupancy": len(z.inside_ids),
                "enter_count": z.enter_count,
                "exit_count": z.exit_count,
                "crowd_threshold": z.crowd_threshold,
                "is_crowded": len(z.inside_ids) >= z.crowd_threshold,
            }
            for z in self.zones
        ]
